# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxfeedback-mvc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '4.4.0'
  pod 'RxCocoa',    '4.4.0'
  pod 'RxFeedback', '2.0.0'

  
end
